In [ ]:
x = 88
y = -8.88
z = 8 + 8*x
print(type(x))
print(type(y))
print(type(z))

In [2]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]]) # Create a 2D array
b = np.array([[7, 8, 9], [10, 11, 12]]) # Create another 2D array
c = np.concatenate((a, b), axis=0) # Concatenate along the first axis
print(c) # Print the concatenated array

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
x = 88
y = -8.88
z = 8 + 8j
print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'float'>
<class 'complex'>


In [1]:
my_list = [1,1.0,"abc",True,[1,1.0],{1},{1:1.0}]
print(f"列表长度：{len(my_list)}")
for index,item in enumerate(my_list):#enumerate()函数返回一个包含索引和元素的元组
    type_i = type(item)
    print(f"element:{item}, index:{index}, type:{type_i}")



列表长度：7
element:1, index:0, type:<class 'int'>
element:1.0, index:1, type:<class 'float'>
element:abc, index:2, type:<class 'str'>
element:True, index:3, type:<class 'bool'>
element:[1, 1.0], index:4, type:<class 'list'>
element:{1}, index:5, type:<class 'set'>
element:{1: 1.0}, index:6, type:<class 'dict'>


# Python中的append方法

`append()`是Python列表(list)对象的一个方法，用于在列表末尾添加一个新元素。

### 语法
```python
list.append(element)
```

### 特点
- 只能添加一个元素到列表末尾
- 直接修改原列表，不返回新列表
- 可以添加任何类型的对象（数字、字符串、列表、字典等）

In [2]:
# 演示append方法的使用

# 创建一个空列表
fruits = []
print(f"初始列表: {fruits}")

# 使用append添加元素
fruits.append("苹果")
print(f"添加一个元素后: {fruits}")

# 继续添加更多元素
fruits.append("香蕉")
fruits.append("橙子")
print(f"添加多个元素后: {fruits}")

# append可以添加任何类型的对象
fruits.append(100)  # 添加数字
fruits.append(["草莓", "蓝莓"])  # 添加列表
fruits.append({"name": "芒果", "color": "黄色"})  # 添加字典
print(f"添加不同类型元素后: {fruits}")

# 注意：append只能一次添加一个元素
print("\n区别：使用append vs 使用extend/+")
list1 = [1, 2, 3]
list2 = [1, 2, 3]
list1.append([4, 5])  # append会将整个列表作为一个元素添加
list2.extend([4, 5])  # extend会将列表中的每个元素分别添加
print(f"使用append: {list1}")
print(f"使用extend: {list2}")

初始列表: []
添加一个元素后: ['苹果']
添加多个元素后: ['苹果', '香蕉', '橙子']
添加不同类型元素后: ['苹果', '香蕉', '橙子', 100, ['草莓', '蓝莓'], {'name': '芒果', 'color': '黄色'}]

区别：使用append vs 使用extend/+
使用append: [1, 2, 3, [4, 5]]
使用extend: [1, 2, 3, 4, 5]


In [3]:
person = {'name': 'Alice', 'age': 30, 'city': 'New York','gender':'male'}
fruits = dict(apple=99, banana=88, orange=77)

print(person['name'])
print(fruits['banana'])

person['name'] = 'Bob'  # 修改字典中的值
print(person)

person['city'] = 'Los Angeles'  # 添加新的键值对
print(person)

del person['age']  # 删除键值对
print(person)

print(person.keys())  # 获取所有键
print(person.values())  # 获取所有值
print(person.items())  # 获取所有键值对

Alice
88
{'name': 'Bob', 'age': 30, 'city': 'New York', 'gender': 'male'}
{'name': 'Bob', 'age': 30, 'city': 'Los Angeles', 'gender': 'male'}
{'name': 'Bob', 'city': 'Los Angeles', 'gender': 'male'}
dict_keys(['name', 'city', 'gender'])
dict_values(['Bob', 'Los Angeles', 'male'])
dict_items([('name', 'Bob'), ('city', 'Los Angeles'), ('gender', 'male')])
