In [ ]:
x = 88
y = -8.88
z = 8 + 8*x
print(type(x))
print(type(y))
print(type(z))

In [2]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]]) # Create a 2D array
b = np.array([[7, 8, 9], [10, 11, 12]]) # Create another 2D array
c = np.concatenate((a, b), axis=0) # Concatenate along the first axis
print(c) # Print the concatenated array

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
x = 88
y = -8.88
z = 8 + 8j
print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'float'>
<class 'complex'>
