In [11]:
import numpy as np

x_array = np.arange(5.0,10,0.1)# Create a 1D array with values from 0 to 9

def functionplus(x):
    return x + 1

print(functionplus(x_array)) # Call the function with the array

[ 6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9  7.   7.1  7.2  7.3
  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3  8.4  8.5  8.6  8.7
  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7  9.8  9.9 10.  10.1
 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.9]


In [12]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]]) # Create a 2D array
b = np.array([[7, 8, 9], [10, 11, 12]]) # Create another 2D array
c = np.concatenate((a, b), axis=0) # Concatenate along the first axis
print(c) # Print the concatenated array

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
