In [11]:
import numpy as np

x_array = np.arange(5.0,10,0.1)# Create a 1D array with values from 0 to 9

def functionplus(x):
    return x + 1

print(functionplus(x_array)) # Call the function with the array

[ 6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9  7.   7.1  7.2  7.3
  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3  8.4  8.5  8.6  8.7
  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7  9.8  9.9 10.  10.1
 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.9]


In [12]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]]) # Create a 2D array
b = np.array([[7, 8, 9], [10, 11, 12]]) # Create another 2D array
c = np.concatenate((a, b), axis=0) # Concatenate along the first axis
print(c) # Print the concatenated array

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [1]:
from sklearn.datasets import load_iris
iris = load_iris() # Load the iris dataset

x = iris.data # Features
type(x) # Check the type of x

y = iris.target # Target variable   
type(y) # Check the type of y

numpy.ndarray

In [4]:
import seaborn as sns

iris_df = sns.load_dataset("iris") # Load the iris dataset using seaborn

print(iris_df.tail()) # Print the first few rows of the dataframe
print(iris_df.head()) # Print the columns of the dataframe
type(iris_df) # Check the type of the dataframe

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica
   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


pandas.core.frame.DataFrame

In [7]:
import copy
a_2_layers = [1,2,[3,4,5]] # Create a list with 2 layers
d_2_layers = a_2_layers.copy() # Create a shallow copy of the list
e_2_layers = copy.deepcopy(a_2_layers) # Create a deep copy of the list

print(a_2_layers is d_2_layers)
print(a_2_layers[2] is d_2_layers[2])

print(a_2_layers is e_2_layers)
print(a_2_layers[2] is e_2_layers[2])


False
True
False
False
